name: make-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        java: [11, 21]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: make tests
      working-directory: ./prism
      run: |
        make
        make unittests
        make tests

  build-win:

    strategy:
      matrix:
        java: [11, 21]
    runs-on: windows-latest

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
    - name: Install Cygwin Dependencies
      uses: cygwin/cygwin-install-action@v4
      with:
        packages: |
          make,
          mingw64-x86_64-gcc-g++,
          binutils,
          dos2unix,
          git,
          wget,
          unzip,
          python
    - name: make tests
      shell: bash
      env:
        CYGWIN: winsymlinks:native
      working-directory: ./prism
      run: >-
        make &&
        make unittests &&
        make tests
